#!/usr/bin/env node
/**
 * Assembles tokens.json from figma-export-data.mjs
 * Generated by Figma MCP use_figma exports.
 */
import { writeFileSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';
import figmaData from './figma-export-data.mjs';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');

const COLLECTIONS = ['Primitive', 'Semantic', 'Component', 'Theme', 'Typography', 'Layout', 'Fluid'];
const data = figmaData;

const exportedAt = new Date().toISOString();
const tokensJson = {
  meta: {
    source: 'Figma',
    fileKey: 'VibdutrclLgS5EpFWgbJhH',
    fileName: 'Portfolio | AI Handoff',
    figmaUrl: 'https://www.figma.com/design/VibdutrclLgS5EpFWgbJhH',
    exportedAt,
    hierarchy: ['Primitive', 'Semantic', 'Component', 'Theme'],
    counts: Object.fromEntries(COLLECTIONS.map((n) => [n, data[n].tokens.length])),
  },
};

for (const name of COLLECTIONS) {
  tokensJson[name] = { modes: data[name].modes, tokens: data[name].tokens };
}

writeFileSync(join(ROOT, 'tokens.json'), JSON.stringify(tokensJson, null, 2) + '\n', 'utf8');
console.log('Wrote tokens.json');
console.log('Counts:', tokensJson.meta.counts);
